[molecule]
  ncenters = 33
  imult = 1
  icharge = 0
  functional = "B3LYP"
  baselabel = "def2svp"
  ecplabel = ""
  basedir = ""
  J = "RI"
  K = "cosx"
  ri_aux_basis = ""
  spherical = true
  harris_guess = true
  calc_force = false
  vv10_nonself = false
  mem_cap_gb = "0.0"
  estimate_only = false
  n_threads = 0
  verbose = 1
  scf_conv_level = 0

[atoms]
  element = [ "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "O", "O", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H" ]
  x = [ "2.90501", "2.42282", "0.89884", "3.08133", "4.58873", "5.22025", "6.61524", "7.40862", "6.77299", "5.38072", "8.92848", "9.47603", "9.62611", "10.73972", "8.95699", "2.40622", "2.69629", "3.98181", "2.67356", "0.58592", "0.41614", "0.51894", "2.79362", "2.68302", "4.62779", "7.07105", "7.35577", "4.91862", "9.20797", "9.24447", "9.05301", "10.5657", "8.07229" ]
  y = [ "3.56427", "2.13997", "2.07338", "1.10906", "1.03886", "0.67243", "0.60767", "0.89995", "1.261", "1.32626", "0.8381", "-0.24283", "2.17304", "2.28212", "3.26412", "4.28099", "3.8548", "3.66192", "1.90136", "2.17799", "2.86971", "1.11615", "1.3328", "0.10739", "0.4297", "0.317", "1.49446", "1.60397", "0.55466", "-0.02551", "-1.2253", "-0.31929", "3.06539" ]
  z = [ "1.63429", "1.91989", "1.78302", "0.98067", "1.08095", "2.2758", "2.35447", "1.23578", "0.0386", "-0.03705", "1.32915", "0.38801", "1.07543", "0.57974", "1.52129", "2.29553", "0.59973", "1.80655", "2.96094", "0.73819", "2.35999", "2.15556", "-0.05587", "1.18981", "3.15552", "3.29964", "-0.85093", "-0.98236", "2.35262", "-0.66009", "0.62899", "0.46845", "1.89199" ]
  basis = [ "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "" ]
  ecp = [ "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "" ]

[pointcharges]
  npc = 0
  q = [ ]
  x = [ ]
  y = [ ]
  z = [ ]

[checkpoint]
  chk_read = false
  chk_write = false
  chk_file = ""

[molden]
  molden_write = false
  molden_file = ""
  molden_read = false
  molden_read_file = ""

[cosmo]
  cosmo_on = false
  cosmo_epsilon = "78.4"
  cosmo_radii_scale = "1.2"
  cosmo_avg_area = "0.3"
  cosmo_sigma_rav = "0.5"
  cosmo_cavity_type = "gepol"
  cosmo_rsolv = "0.0"
  cosmo_ks_nseg = 92
  cosmo_ks_nface = 1082
  cosmo_sigma_profile_file = ""
  cosmo_solvent = ""
  cosmo_smd = false

[environment]
  ENGINE_RESP_DUMP = "/tmp/claude-1000/-home-xchen-Work-Engine/1c11a618-2f52-4fd3-acf4-473fddb7c220/scratchpad/eng_resp"
